#lang racket
(provide (all-defined-out) (all-from-out racket))
(require compatibility/defmacro)
(require srfi/9)

(define-macro (復名詞法 名 原) `(define-macro (,名 . 參) (cons ',原 參)))
(復名詞法 定 define)
(復名詞法 定表 define-record-type)
(復名詞法 名 let)
(復名詞法 名眾 letrec)
(復名詞法 始 begin)
(定 錯 error)

(復名詞法 入 λ)
(定 用 apply)
(定 入？ procedure?)

(定 首 car)
(定 尾 cdr)
(定 首尾 cons)
(定 首尾？ pair?)
(定 空 '())
(定 空？ null?)
(定 列？ list?)
(定 列 list)
(定 連 append)
(定 簡 filter)
(定 遍 map)
(定 第一 first)
(定 第二 second)
(定 第三 third)

(復名詞法 或 or)
(復名詞法 皆 and)
(復名詞法 若 if)
(復名詞法 若. cond)
(定 否則 #t)
(define-macro (若等. x . xs)
     (cons 'case (cons x (map (λ (x) (if (list? (car x)) x (cons 'else (cdr x)))) xs))))
(定 陰陽？ boolean?)
(定 陰 #f)
(定 陽 #t)
(定 (等？ 甲 乙 . 集)
   (皆 (或 (equal? 甲 乙) (= 甲 乙))
      (或 (空？ 集) (用 等？ 乙 集))))

(定 數？ number?)
(定 加 +)
(定 減 -)
(定 乘 *)
(定 除 /)
(定 小？ <)
(定 大？ >)
(定 小等？ <=)
(定 大等？ >=)
(定 數→串 number->string)
(定 串→數 number->string)

(定 字？ char?)
(定 串？ string?)
(定 串 string)
(定 列→串 list->string)
(定 串→列 string->list)

(定 符？ symbol?)
(定 串→符 string->symbol)
(定 符→串 symbol->string)

(定 映 hash)
(定 映？ hash?)
(定 映-取 hash-ref)
(定 映-改 hash-set)
(定 映-有？ hash-has-key?)
(定 映→列 hash->list)
(定 列→映 make-immutable-hash)
