#!/bin/sh
#  Copyright (C) 2017  Zaoqi

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#scm2lua "导出的 ..." 文件 ...

f=$(mktemp)
exports="$1"
shift
echo '(' > $f
cat "$@" >> $f
cd $(dirname "$0")
echo >> $f
echo -n "(hash" >> $f
for e in $exports ;do
	echo -n " (quote $e) $e" >> $f
done
echo '))' >> $f
cat $f | racket lua.rkt
rm $f
