(require compatibility/defmacro)
(require srfi/9)
(define-macro (譯詞法 名 原) `(define-macro (,名 . 參) (cons ',原 參)))
(譯詞法 定 define)
(譯詞法 定表 define-record-type)
(譯詞法 若 if)
(譯詞法 或 or)
(譯詞法 皆 and)
(譯詞法 名 let)
(譯詞法 名眾 letrec)
(定 首 car)
(定 尾 cdr)
(定 建 cons)
(定 陰 #f)
(定 陽 #t)